services:
  app:
    build: .
    ports:
      - "2140:22"
    volumes:
      - ./app:/home/dockeruser/app
    container_name: my_docker_container
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    # Alternatively, use the 'gpus' key directly:
    # gpus: all